### ISSUE TITLE
DreamCaster tool not working

### ISSUE THREAD

**Issue by JulianFhofer** [3dct/open_iA-superbuild#3]
Hello everyone,

im stuck at trying to get the DreamCaster module ready to work. I did everything as proposed within the superbuild instructions. Also did I enable the OPENCL on CMake as it says that the DreamCaster depends on it. After creating the bins and building the open_iA_superbuild solution in msvc2017 it shows 5 successfull and 3 failed (OpenCL_ICD, ITK and open_iA) builds. Also i've already built the solution without having the OPENCL module activated on CMake. However, the DreamCaster did not appear within the built data.

Are there some other additional modules that have to be activated in CMake in order to make the DreamCaster work? Am I missing something?

Best regards,
Julian

**Comment by codeling** [comment]
Hi there!

In the superbuild solution, the open_iA project includes not only the open_iA core libraries and binaries, but also all modules; since DreamCaster is one such module of open_iA, it is not listed as a separate project in the superbuild solution, but it will be built from within the open_iA project.

To see all separate module projects, you can open the `open_iA\bin\open_iA.sln` solution from within the superbuild binaries folder (after the superbuild has run at least once).
Once the superbuild has succeeded to build all the prerequisites, using this `open_iA\bin\open_iA.sln` solution is recommended, if you later want to develop something inside open_iA (as once the prerequisites are built, they typically don't need to be checked for a rebuild). The main goal behind the superbuild solution is to quickly set up a working build enviroment, not to use it for daily development in open_iA (currently this is not well-documented yet, I know).

There currently is an issue with the OpenCL build in the superbuild, where the way the source fetching is set up won't allow it to build properly the first time a build is triggered; I am working on a fix right now; in the meantime, it should also build fine when you trigger the build again (i.e. just running "Build solution" a second time).

As for the ITK build error, what error messages do you get?

By the way, for trying DreamCaster, you can use [our latest binary release](https://github.com/3dct/open_iA/releases).

**Comment by codeling** [comment]
The OpenCL issue on first build should be fixed by commit 5262c1b30a9ad3e78ff1a297e8fdb12a041a5e97

If it is still not working, let me know what error messages you get!

**Comment by JulianFhofer** [comment]
Highly appreciate the immediate help, thanks. The second build was what was missing and its working as desired now. 

ITK error messages from the first build:

6>c:\bins\itk\src-5.0.1\modules\core\gpucommon\include\itkOpenCLUtil.h(36): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "CL/opencl.h": No such file or directory [C:\Bins\itk\bin-5.0.1\Modules\Core\GPUCommon\src\ITKGPUCommon.vcxproj]
6>c:\bins\itk\src-5.0.1\modules\core\gpucommon\include\itkOpenCLUtil.h(36): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "CL/opencl.h": No such file or directory [C:\Bins\itk\bin-5.0.1\Modules\Core\GPUCommon\src\ITKGPUCommon.vcxproj]
6>c:\bins\itk\src-5.0.1\modules\core\gpucommon\include\itkOpenCLUtil.h(36): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "CL/opencl.h": No such file or directory [C:\Bins\itk\bin-5.0.1\Modules\Core\GPUCommon\src\ITKGPUCommon.vcxproj]
6>C:\Bins\itk\src-5.0.1\Modules\Core\GPUCommon\include\itkOpenCLUtil.h(36): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "CL/opencl.h": No such file or directory [C:\Bins\itk\bin-5.0.1\Modules\Core\GPUCommon\src\ITKGPUCommon.vcxproj]
6>c:\bins\itk\src-5.0.1\modules\core\gpucommon\include\itkOpenCLUtil.h(36): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "CL/opencl.h": No such file or directory [C:\Bins\itk\bin-5.0.1\Modules\Core\GPUCommon\src\ITKGPUCommon.vcxproj]
6>Die Erstellung des Projekts "ITK.vcxproj" ist abgeschlossen -- FEHLER.

Here's the file containing the entire build log for further information:
[firstbuild.txt](https://github.com/3dct/open_iA-superbuild/files/4457492/firstbuild.txt)

**Comment by codeling** [comment]
Thanks for the output!
This indeed looks like the ITK build just failed because of the failed OpenCL build, and the open_iA build in turn probably failed because of the unfinished ITK build.

In short, the abovementioned commit should fix all that for the future, so I will close this issue!

Thanks for reporting, and let us know how your experiments with the DreamCaster module go!
